---
title: "YouTube communication of Italian Political Parties"
author: "Maria Ascolese"
date: "March 11, 2022"
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
    highlight: tango

header-includes:
 \usepackage{fancyhdr}
 \pagestyle{fancy}
 \fancyhead[LE,LO]{YouTube communication of Italian Political Parties}
 \fancyhead[RE,RO]{Maria Ascolese - 01095A}
---

```{r setup, eval=FALSE, include=TRUE}

```

<br> 

# Introduction

In this paper I use the `YouTube Data API v3` to collect data and metadata from the official YouTube channels of major Italian Parties in order to investigate content and language occurrences in YouTube videos. The goal of this short analysis would be to understand each Party's topics and language of choice, and I believe that their YouTube channels might be accurate small representations of their communicative goals, as all video content on the channels has been necessarily chosen and published by the channel owner and, therefore, intentionality must be assumed (Vesnic-Alujevic & Van Bauwel, 2014).



# Hypotheses

*H1* Parties with common ideologies also show common keywords, emotional words and syntax.

*H2* Each party's keywords, emotional words and syntax change dramatically over time.


# Data

I used the R package `Tuber` to collect YouTube videos data. `Tuber` consists of a number of functions useful to extract data from the YouTube platform via the YouTube Data API v3. I conducted the queries using each political party's ID in the `list_channel_videos` function, which resulted in obtaining metadata for each video published on every channel. The tool provided metadata for 20000 videos from [**Movimento 5 Stelle**](https://www.youtube.com/user/M5SParlamento)'s channel; 9548 videos from [**Lega Salvini Premier**](https://www.youtube.com/c/LegaSalviniPremier)'s channel; 1955 videos from [**Partito Democratico**](https://www.youtube.com/c/PartitoDemocratico)'s channel; 5555 videos from [**Fratelli d'Italia**](https://www.youtube.com/c/FratellidItaliaAN)'s channel; 67 videos from [**Forza Italia**](https://www.youtube.com/c/forzaitalia)'s channel.

Since `Tuber`'s function to extract subtitles from YouTube videos has been recently disable, I used the R package `youtubecaptions` instead. The function `get_captions` gives back a number of string characters for each video, which correspond to the unique captions appearing on the screen as the video plays. I then joined them in single string characters, obtaining whole transcriptions for each video of the channels.



# Methods

After [preparing the data](https://github.com/DataAccess2020/YT-API/blob/main/Scripts/01_data_preparation.R) in order to have clean, tidy datasets for each political party's channel, I finally came to the analysis, for which I used the `tidytext` package.

For each party's channel, I split the captions in words in order to remove stopwords (like conjunctions and auxiliary verbs, but also some adverbs that I manually added to the list), I removed encoding errors (like some accent marks) and some YouTube transcription errors (like numbers being transcripted with digits instead of words). When I finally ended up with clean lexemes of interest, for each party I obtained the `count` of each word and sorted them. To a first look, it appeared that the most frequent words were common between the parties: lavoro, partito and persone, to name a few.

At this point, I was ready to visualize the data. In order to look into my first hypothesis, I wanted to compare the frequency of words between parties. However, the number of videos uploaded by each party varies significantly: to make an example, the most recurrent word for Forza Italia is ***, which occurs 104 times in 60 videos, meanwhile the most recurrent word for Lega is ***, which occurs n in n videos. To make these numbers impartial and comparable, I decided to get the in-group percentage of occurrance of each word. For example, Forza Italia's *** percentage of appearance is 104/n, which is comparable to Lega's *** appearance of n/n.



# Results



# Conclusion



# References
